In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]
a

[1, 2, 3]

In [3]:
b = [[1,2,3], [4,5,6], [7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
na = np.array(a)
na

array([1, 2, 3])

In [5]:
naa = na.astype(np.int8)
naa

array([1, 2, 3], dtype=int8)

In [6]:
naa.shape

(3,)

In [8]:
naaa = np.expand_dims(naa, axis=0)
naaa

array([[1, 2, 3]], dtype=int8)

In [9]:
naaa.shape

(1, 3)